import type { Metadata } from "next";
// 1. IMPORT FONT (INI SUDAH BENAR)
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { Providers } from "./providers"; // Ini provider Chakra UI Anda

// 2. HAPUS SEMUA BLOK "const geistSans = ..." DAN "const geistMono = ..."
//    YANG SEBELUMNYA ADA DI SINI.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/*
        3. GANTI CLASSNAME DI BODY
           UNTUK MEMAKAI "GeistSans.variable" LANGSUNG (HURUF BESAR)
      */}
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}